// Code generated by protoc-gen-go. DO NOT EDIT.
// source: socket.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Payload struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Payload)(nil), "pb.Payload")
}

func init() { proto.RegisterFile("socket.proto", fileDescriptor_6b39cc5e3943e1cc) }

var fileDescriptor_6b39cc5e3943e1cc = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0x4f, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe6, 0x62,
	0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x41, 0x8a, 0x02, 0x12, 0x2b,
	0x73, 0xf2, 0x13, 0x53, 0x70, 0x2b, 0x32, 0xb2, 0xe1, 0xe2, 0x0d, 0x06, 0x9b, 0x1e, 0x9c, 0x5a,
	0x54, 0x96, 0x99, 0x9c, 0x2a, 0xa4, 0xcd, 0xc5, 0x19, 0x52, 0x94, 0x98, 0x57, 0x5c, 0x90, 0x5f,
	0x54, 0x22, 0xc4, 0xad, 0x57, 0x90, 0xa4, 0x07, 0xb5, 0x49, 0x0a, 0xcc, 0x81, 0x9a, 0xa8, 0xc4,
	0xa0, 0xc1, 0x68, 0xc0, 0x98, 0xc4, 0x06, 0x76, 0x92, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa8,
	0xf1, 0x72, 0x00, 0xa2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SocketServiceClient is the client API for SocketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SocketServiceClient interface {
	Transport(ctx context.Context, opts ...grpc.CallOption) (SocketService_TransportClient, error)
}

type socketServiceClient struct {
	cc *grpc.ClientConn
}

func NewSocketServiceClient(cc *grpc.ClientConn) SocketServiceClient {
	return &socketServiceClient{cc}
}

func (c *socketServiceClient) Transport(ctx context.Context, opts ...grpc.CallOption) (SocketService_TransportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SocketService_serviceDesc.Streams[0], "/pb.SocketService/Transport", opts...)
	if err != nil {
		return nil, err
	}
	x := &socketServiceTransportClient{stream}
	return x, nil
}

type SocketService_TransportClient interface {
	Send(*Request) error
	Recv() (*Payload, error)
	grpc.ClientStream
}

type socketServiceTransportClient struct {
	grpc.ClientStream
}

func (x *socketServiceTransportClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *socketServiceTransportClient) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SocketServiceServer is the server API for SocketService service.
type SocketServiceServer interface {
	Transport(SocketService_TransportServer) error
}

// UnimplementedSocketServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSocketServiceServer struct {
}

func (*UnimplementedSocketServiceServer) Transport(srv SocketService_TransportServer) error {
	return status.Errorf(codes.Unimplemented, "method Transport not implemented")
}

func RegisterSocketServiceServer(s *grpc.Server, srv SocketServiceServer) {
	s.RegisterService(&_SocketService_serviceDesc, srv)
}

func _SocketService_Transport_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SocketServiceServer).Transport(&socketServiceTransportServer{stream})
}

type SocketService_TransportServer interface {
	Send(*Payload) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type socketServiceTransportServer struct {
	grpc.ServerStream
}

func (x *socketServiceTransportServer) Send(m *Payload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *socketServiceTransportServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SocketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SocketService",
	HandlerType: (*SocketServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transport",
			Handler:       _SocketService_Transport_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "socket.proto",
}
